### ISSUE TITLE
Missing button & wrong version no

### ISSUE THREAD

**Issue by tapanis** [openlilylib/LO-ly#19]
I updated to the latest version (3.5.7) - and my OLy button disappeared. Moreover, the extension manager reported the version as 3.5.6.

I removed the extension and downloaded 3.5.6, and the button reappeared.

**Comment by KlausBlum** [comment]
Thanks for your report. 

I'm surprised by the version numbers 3.5.6 and 3.5.7 - did you mean **0**.5.6 and **0**.5.7 or are they really reported as 3.5.X? 
The reported "old" version number 0.5.6 is a mistake by me, I simply forgot to update it to 0.5.7 - oops...

However, it is strange for me to read that the OLy button does not appear in 0.5.7 because the release was made to fix that very detail. 
Could you please tell me which OpenOffice/LibreOffice you are working on and what your operating system is (Windows/Linux/Mac)?

BTW: You can safely go back to 0.5.6 whithout missing anything. The only change on 0.5.7 was that OLy button thing that apparently doesn't work as intended. 

Cheers, 
Klaus

**Comment by tapanis** [comment]
Hi Klaus. Thanks for your reply (and sorry for not getting back straight away).

Yes, that was my typo. Should have read 0.5.6/7.

I'm using LibreOffice 6.0.5.2 rc from a ppa on the latest release of Ubuntu.

Ironically, if I remove 0.5.7 and re-install 0.5.6, the button comes back - not the other way round. So I'll do that for now.

I really appreciate your reviving this tool! I use it a lot.

Tapani

**Comment by KlausBlum** [comment]
Hi Tapani, 

when I tested OLy 0.5.7, I was using LibreOffice 6.0.2.1 (which seems to have a strange behaviour regarding toolbars - you cannot delete existing toolbars). 
I now have upgraded to LibreOffice 6.0.4.2 and found out that i have exactly the same problem as you. :)

I've done some more testing: It seems that the method for toolbar creation that OLy used until 0.5.6 was just fine for LibreOffice. (It's the file LO-ly/extension/Addons.xcu in the repo.)
The "new" method introduced in OLy 0.5.7 seems to work _only_ for Apache OpenOffice. 
So for now, I'll probably create different releases for LibreOffice and OpenOffice. Let's see if there will be any development in future LibreOffice/OpenOffice versions. 

In addition, maybe I'll create a step-by-step guide how to manually create a toolbar with an OLy button, just to be prepared for any worst-case...

Best wishes, 
Klaus

**Comment by KlausBlum** [comment]
Done. 
[Release 0.5.8](https://github.com/openlilylib/LO-ly/releases/tag/0.5.8) offers two `*.oxt` files: 
One for LibreOffice with toolbar creation as in 0.5.6 and before, 
one for OpenOffice with toolbar creation as in 0.5.7. 

Let's see if it's worth to keep up a dedicated OpenOffice version in future releases...
