### ISSUE TITLE
Creating OXT files

### ISSUE THREAD

**Issue by KlausBlum** [openlilylib/LO-ly#3]
Apparently, renaming the automatically created ZIP file to OXT does **not** create a working installatin file for the extension. 
Using an existing OXT to ZIP, replacing files with their updated versions, renaming back zu OXT should work.

**Comment by joram-berger** [comment]
With automatically, you mean what github offers for download? We should find out why. The file produced with `make` produces a working installation here. Perhaps some files are not allowed in the oxt file?

**Comment by KlausBlum** [comment]
Yes, I meant the ZIP file github offers for download. 
I think I got it now: Inside the ZIP, there is an additional subfolder which contains everything that should be in the root directory. Packing the contents of the subfolder into a ZIP and renaming to OXT works fine. Thus, no illegal ingredients, but there will always be the need of some manual work.

**Comment by joram-berger** [comment]
I hoped that would be the benefit of moving everything to the main directory. Since that obviously does not work, I have no objections against reintroducing the development folder (or perhaps called "extension" which contains all files to put into the oxt file. Then you have it easier also without make.
